### PR TITLE
swift.php correction email html body display

### PR DESCRIPTION
**Pull request by AntonLinderer**
html body as default specified now with text as fallback for email

### CODE REVIEW

**Comment by aimeos** [comment]
Everything seems OK and working now. Thank you very much! :-)
We will also push this to 2017.10 and 2018.01

**Comment by aimeos** [comment]
New versions are released

**Comment by AntonLinderer** [comment]
No worries! Aimeos is great software!

**Comment by aimeos** [comment]
Thanks, it's good to know that you love it the same way we do :-)

**Pull request merged**
